[package]
name = "tpi"
version = "2.0.2"
edition = "2021"
description = "The Package Index"

[dependencies]
sorbet_kvp = "1.0.1"
anyhow = "1.0.97"
colored = "3.0.0"
reqwest = { version = "0.12.13", features = ["blocking"] }
tempfile = "3.18.0"
